<a href="https://colab.research.google.com/github/prakashpoudyal/All-CSV-ML-Data-Files-Download/blob/master/Churn_Modelling_Project_(Kaggle).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Flatten, Dense

In [0]:
print(tf.__version__)

2.2.0


In [0]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

In [0]:
from google.colab import files 
upload = files.upload()

Saving datasets_13214_17927_Churn_Modelling.csv to datasets_13214_17927_Churn_Modelling.csv


In [0]:
dataset=pd.read_csv('/content/datasets_13214_17927_Churn_Modelling.csv')

In [0]:
dataset.head()

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [0]:
dataset.tail()

RowNumber  CustomerId    Surname  ...  IsActiveMember EstimatedSalary Exited
9995       9996    15606229   Obijiaku  ...               0        96270.64      0
9996       9997    15569892  Johnstone  ...               1       101699.77      0
9997       9998    15584532        Liu  ...               1        42085.58      1
9998       9999    15682355  Sabbatini  ...               0        92888.52      1
9999      10000    15628319     Walker  ...               0        38190.78      0

[5 rows x 14 columns]

In [0]:
dataset.EstimatedSalary

0       101348.88
1       112542.58
2       113931.57
3        93826.63
4        79084.10
          ...    
9995     96270.64
9996    101699.77
9997     42085.58
9998     92888.52
9999     38190.78
Name: EstimatedSalary, Length: 10000, dtype: float64

In [0]:
X=dataset.drop(labels=['CustomerId','Surname','RowNumber','Exited'], axis=1)
y=dataset['Exited']

In [0]:
y.head()

0    1
1    0
2    1
3    0
4    0
Name: Exited, dtype: int64

In [0]:
from sklearn.preprocessing import LabelEncoder
label1=LabelEncoder()


In [0]:
X['Geography']=label1.fit_transform(X['Geography'])
X.Geography

0       0
1       2
2       0
3       0
4       2
       ..
9995    0
9996    0
9997    0
9998    1
9999    0
Name: Geography, Length: 10000, dtype: int64

In [0]:
label=LabelEncoder()
X['Gender']=label.fit_transform(X['Gender'])
X.head(10)

CreditScore  Geography  Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0          619          0       0  ...          1               1        101348.88
1          608          2       0  ...          0               1        112542.58
2          502          0       0  ...          1               0        113931.57
3          699          0       0  ...          0               0         93826.63
4          850          2       0  ...          1               1         79084.10
5          645          2       1  ...          1               0        149756.71
6          822          0       1  ...          1               1         10062.80
7          376          1       0  ...          1               0        119346.88
8          501          0       1  ...          0               1         74940.50
9          684          0       1  ...          1               1         71725.73

[10 rows x 10 columns]

In [0]:
df.isna()

NameError: ignored

In [0]:
dataset.isna().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [0]:
###Feature Standardization

In [0]:
from sklearn.preprocessing import StandardScaler

In [0]:
X_train, X_test, y_train, y_test=train_test_split(X, y, test_size=0.2, random_state=0, stratify=y)

In [0]:
scaler=StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [0]:
X_train

array([[-1.24021723, -0.90267262, -1.09665089, ..., -1.54963239,
        -1.03849022,  1.64099027],
       [ 0.75974873,  0.30491617,  0.91186722, ...,  0.64531434,
         0.96293637, -1.55587522],
       [-1.72725557, -0.90267262, -1.09665089, ...,  0.64531434,
        -1.03849022,  1.1038111 ],
       ...,
       [-0.51484098,  0.30491617,  0.91186722, ..., -1.54963239,
         0.96293637, -1.01507508],
       [ 0.73902369, -0.90267262, -1.09665089, ...,  0.64531434,
         0.96293637, -1.47887193],
       [ 0.95663657,  1.51250495,  0.91186722, ...,  0.64531434,
        -1.03849022,  0.50945854]])

## **Build ANN**

In [0]:
model=Sequential()
model.add(Dense(X.shape[1],activation='relu', input_dim=X.shape[1]))
model.add(Dense(128,activation='relu'))
model.add(Dense(1, activation='sigmoid'))

In [0]:
X.shape[1]

10

In [0]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [0]:
model.fit(X_train, y_train.to_numpy(), batch_size=10, epochs=10, verbose= 1 )

Epoch 1/10
800/800 [==============================] - 1s 1ms/step - loss: 0.3257 - accuracy: 0.8692
Epoch 2/10
800/800 [==============================] - 1s 1ms/step - loss: 0.3239 - accuracy: 0.8651
Epoch 3/10
800/800 [==============================] - 1s 1ms/step - loss: 0.3234 - accuracy: 0.8664
Epoch 4/10
800/800 [==============================] - 1s 1ms/step - loss: 0.3224 - accuracy: 0.8670
Epoch 5/10
800/800 [==============================] - 1s 1ms/step - loss: 0.3224 - accuracy: 0.8664
Epoch 6/10
800/800 [==============================] - 1s 1ms/step - loss: 0.3208 - accuracy: 0.8695
Epoch 7/10
800/800 [==============================] - 1s 1ms/step - loss: 0.3208 - accuracy: 0.8660
Epoch 8/10
800/800 [==============================] - 1s 1ms/step - loss: 0.3204 - accuracy: 0.8677
Epoch 9/10
800/800 [==============================] - 1s 1ms/step - loss: 0.3196 - accuracy: 0.8686
Epoch 10/10
800/800 [==============================] - 1s 1ms/step - loss: 0.3192 - accuracy: 0.8702

In [0]:
y_pred=model.predict_classes(X_test)

Instructions for updating:
Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).


In [0]:
y_pred

array([[0],
       [0],
       [0],
       ...,
       [0],
       [1],
       [0]], dtype=int32)

In [0]:
y_test

1344    1
8167    0
4747    0
5004    1
3124    1
       ..
9107    0
8249    0
8337    0
6279    1
412     0
Name: Exited, Length: 2000, dtype: int64

In [0]:
model.evaluate(X_test, y_test)

63/63 [==============================] - 0s 1ms/step - loss: 0.3576 - accuracy: 0.8525


[0.3576495349407196, 0.8525000214576721]

In [0]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [0]:
confusion_matrix(y_test, y_pred)

array([[1514,   79],
       [ 217,  190]])

In [0]:
confusion_matrix(y_train, y_train)

array([[6370,    0],
       [   0, 1630]])

**Precision and Recall and F-measure**

In [0]:
from sklearn.metrics import classification_report

In [0]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.87      0.95      0.91      1593
           1       0.71      0.47      0.56       407

    accuracy                           0.85      2000
   macro avg       0.79      0.71      0.74      2000
weighted avg       0.84      0.85      0.84      2000

