<a href="https://colab.research.google.com/github/prakashpoudyal/All-CSV-ML-Data-Files-Download/blob/master/SimpleNeuralNetworkExample.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np


In [32]:
np.exp(-0.20646505)

0.8134546912016059

In [0]:
def sigmoid(x):
  return 1/(1*np.exp(-x))

In [0]:
training_inputs=np.array([[0,0,1], [1,1,1],[1,0,1],[0,1,1] ])

In [5]:
training_inputs

array([[0, 0, 1],
       [1, 1, 1],
       [1, 0, 1],
       [0, 1, 1]])

In [0]:
training_outputs=np.array([[0,1,1,0]]).T

In [9]:
training_outputs

array([[0],
       [1],
       [1],
       [0]])

In [0]:
ran=np.random.seed(1)

In [13]:
print(ran)

None


In [0]:
synaptic_weights=2*np.random.random((3,1))-1

In [39]:
synaptic_weights

array([[-0.5910955 ],
       [ 0.75623487],
       [-0.94522481]])

In [40]:
print("Random starting synaptic weights:")

Random starting synaptic weights:


In [41]:
print(synaptic_weights)

[[-0.5910955 ]
 [ 0.75623487]
 [-0.94522481]]


In [3]:
import numpy as np

class NeuralNetwork():

  def __init__(self):
    np.random.seed(1)
    self.synaptic_weight = 2 * np.random.random((3,1))-1

  def sigmoid(self, x):
    return 1/ (1+np.exp(-x))

  def sigmoid_derivative(self, x):
    return x* (1-x)

  def train(self, trainin_inputs, trainin_outputs, training_iterations):

    for iteration in range(training_iterations):

      output =self.think(trainin_inputs)
      error=trainin_outputs -output
      adjustments= np.dot(training_inputs.T, error *self.sigmoid_derivative(output))
      self.synaptic_weight +=adjustments

  def think(self, inputs):
    inputs=inputs.astype(float)
    output=self.sigmoid(np.dot(inputs, self.sysnaptic_weights))

    return output

if __name__=="__main__":
  neural_network=NeuralNetwork()

  print("Random Synaptic Weights:")
  print(neural_network.synaptic_weights)

  training_inputs=np.array([[0,0,1], [1,1,1], [1,0,1],[0,1,1]])

  training_outputs=np.array([[0,1,1,0]]).T

  neural_networ.train(trainin_inputs, training_outputs, 10000)

  print("Synaptic Weights training")
  print(neural_network.synaptic_weights)

  A=str(input("Input 1: "))
  B=str(input("Input 2: "))
  C=str(input("Input 3: "))

  print("New situation: input data= ", A,B,C)
  print("Output data: ")
  print(neural_network.think(np.array([A,B,C])))





Random Synaptic Weights:


AttributeError: ignored

In [29]:
np.dot(2)

TypeError: ignored

In [27]:
for iteration in range(4):
  print(iteration)

0
1
2
3
